Classes = [
    {
        "cid": "{4a73d4d4-09fd-4f68-8c31-a6b39bfb36b7}",
        "contract_ids": ["@mozilla.org/felt;1"],
        "esModule": "resource://gre/modules/Felt.sys.mjs",
        "constructor": "FeltCls",
        "categories": {"app-startup": "FeltSingleton"},
        "processes": ProcessSelector.MAIN_PROCESS_ONLY,
    },
]
