# -*- Mode: python; indent-tabs-mode: nil; tab-width: 40 -*-
# vim: set filetype=python:
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        'cid': '{32448648-9fb5-4e17-8b71-31ce4183a18c}',
        'contract_ids': ['@mozilla.org/browser/enterprise-forced-quit;1'],
        'esModule': 'resource:///modules/enterprise/EnterpriseForcedQuit.sys.mjs',
        'constructor': 'EnterpriseForcedQuitStartup',
        'categories': {'app-startup': 'EnterpriseForcedQuit'},
        'processes': ProcessSelector.MAIN_PROCESS_ONLY,
    },
]
