#!/usr/bin/env python3

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

"""Replicate the outcome of one task of the try push of this branch.

Generated by try-status-gen, one per task of the try push, and run by the queue
once the task it monitors has resolved: the whole wait is a dependency, so there
is nothing to poll here. It copies the status and the logs of that task, points
at it with an artifact, and exits with its outcome.

This file is read by try-status-gen and embedded in the tasks it generates, so
it runs without a checkout and must stay standard library only.
"""

import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request

USER_AGENT = "enterprise-try-status (+https://github.com/mozilla/enterprise-firefox)"

ARTIFACTS = os.environ.get("MOZ_UPLOAD_DIR", "/builds/worker/artifacts")
# Logs of a try task run to tens of megabytes, and this is a copy of one, so the
# tail is dropped rather than moving the whole thing for every task of a push.
MAX_LOG_BYTES = 20 * 1024 * 1024
CHUNK = 1024 * 1024
# `live.log` redirects to `live_backing.log` and `certified.log` repeats it for
# chain of trust, so copying either would move the same bytes twice.
SKIPPED_LOGS = frozenset({"public/logs/live.log", "public/logs/certified.log"})
# Resolutions that say nothing about the change being tested.
INFRA_REASONS = frozenset({
    "claim-expired",
    "deadline-exceeded",
    "internal-error",
    "intermittent-task",
    "resource-unavailable",
    "worker-shutdown",
})


def log(message):
    print(message, flush=True)


def get(url):
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    return urllib.request.urlopen(request, timeout=120)


def get_json(url):
    with get(url) as response:
        return json.load(response)


def write(name, content):
    os.makedirs(ARTIFACTS, exist_ok=True)
    with open(os.path.join(ARTIFACTS, name), "w", encoding="utf-8") as handle:
        handle.write(content)


def copy_logs(root_url, task_id, run_id):
    """Bring the logs of the monitored task over as artifacts of this one."""
    url = f"{root_url}/api/queue/v1/task/{task_id}/runs/{run_id}/artifacts"
    for entry in get_json(url).get("artifacts", []):
        name = entry["name"]
        if not name.startswith("public/logs/") or name in SKIPPED_LOGS:
            continue
        target = os.path.join(ARTIFACTS, os.path.basename(name))
        source = "{}/api/queue/v1/task/{}/runs/{}/artifacts/{}".format(
            root_url, task_id, run_id, urllib.parse.quote(name, safe="")
        )
        copied = 0
        try:
            with get(source) as response, open(target, "wb") as handle:
                while copied < MAX_LOG_BYTES:
                    chunk = response.read(min(CHUNK, MAX_LOG_BYTES - copied))
                    if not chunk:
                        break
                    handle.write(chunk)
                    copied += len(chunk)
                if response.read(1):
                    handle.write(
                        f"\n[truncated at {MAX_LOG_BYTES} bytes, see {task_id}]\n".encode()
                    )
                    log(f"{name} was truncated at {MAX_LOG_BYTES} bytes")
        except urllib.error.HTTPError as error:
            log(f"Could not copy {name}: {error}")
            continue
        log(
            f"Copied {name} ({copied} bytes) to public/try-status/{os.path.basename(name)}"
        )


def main():
    root_url = os.environ["TASKCLUSTER_ROOT_URL"].rstrip("/")
    task_id = os.environ["TRY_STATUS_TASK_ID"]
    label = os.environ.get("TRY_STATUS_TASK_LABEL", task_id)
    task_url = os.environ.get("TRY_STATUS_TASK_URL", "")

    status = get_json(f"{root_url}/api/queue/v1/task/{task_id}/status")["status"]
    state = status["state"]
    runs = status.get("runs") or []
    run_id = runs[-1]["runId"] if runs else 0
    reason = runs[-1].get("reasonResolved") if runs else None

    inspector = f"{root_url}/tasks/{task_id}/runs/{run_id}"
    log(f"{label} is {state} ({reason})")
    log(f"  task     {inspector}")
    log(f"  treeherder {task_url}")

    write(
        "original-task.json",
        json.dumps(
            {
                "label": label,
                "taskId": task_id,
                "runId": run_id,
                "state": state,
                "reasonResolved": reason,
                "taskUrl": inspector,
                "treeherderUrl": task_url,
            },
            indent=2,
        ),
    )
    write(
        "original-task.html",
        "<!doctype html><meta charset=utf-8>"
        f"<title>{label}</title>"
        f"<p><a href='{inspector}'>{label} on enterprise-firefox-try</a>"
        f"<p><a href='{task_url}'>the same task on Treeherder</a>\n",
    )

    copy_logs(root_url, task_id, run_id)

    if state == "completed":
        return 0
    if reason == "superseded":
        log("Superseded on try, nothing to report")
        return 0
    if reason in INFRA_REASONS:
        log("Infrastructure failure on try, not a result for this branch")
        return 0
    return 1


if __name__ == "__main__":
    sys.exit(main())
